### ISSUE TITLE
HTTP ERROR 406

### ISSUE THREAD

**Issue by TentativeConvert** [Frimkron/PHPCalFeed#8]
I followed the installation instructions, i.e. I copied the files `calendar-cal.css`, `calendar-sub.css`,  `calendar-sub.png`, `calendar.php` and  `calendar.xsd` to a folder `PHPCalFeed-master` on my web server, and put a calendar `calendar-master.ics` in the same folder.  

As far as I can tell, my server meets the installation requirements, i.e. it has a sufficiently recent version of php installed and `calendar.php` has write access to the folder `PHPCalFeed-master`.  

I verified this as follows:  An auxiliary php-file in `PHPCalFeed-master` with contents

    <?php echo 'Current PHP version: ' . phpversion(); ?>
    <br>
    <?php echo `whoami`; ?>

displays as 

     Current PHP version: 7.0.33-0ubuntu0.16.04.7
     www-data 

in my browser, and  `ls -l ../ && ls -l calendar.php `returns:

    drwxr-xr-x 2 www-data 1001   4096 Dec  6 15:28 PHPCalFeed-master
    -rwxr-xr-x 1 www-data 1001 183214 Dec 14  2014 calendar.php

However, when I try to open `calendar.php` in my browser, I get the error message `HTTP ERROR 406`.  Any ideas what I'm doing wrong?  How could I debug this?

**Comment by Frimkron** [comment]
Hi @TentativeConvert. The `calendar.php` file needs to be in the same directory as the other files. Off the top of my head I'm not sure why that would result in a 406 response, but that's the first thing I would try.

Http 406 means "Not Acceptable" which indicates that the script has tried to determine what output format to respond with, based on the "Accept" header your browser sent in the request, and the formats it is capable of producing with the libraries available to your php installation, but wasn't able to find a match. 

Normally the browser would ask for HTML format, so I'm thinking maybe one of the required libraries for HTML output is missing (and I forgot to mention it in the readme). You can find detailed information about your php environment by putting a call to the `phpinfo` function in your test script. In the list of installed extensions you'll want to check that `libxml` and `dom` are there. Calfeed uses an XML Dom tree to generate HTML.

If that still doesn't resolve the problem, it could be a bug in my script. To help diagnose it further, If be interested to know what the `HTTP_ACCEPT` variable was set to in phpinfo - in other words what Accept header the browser sent, which possibly wasn't parsed correctly.

**Comment by TentativeConvert** [comment]
Thanks a lot for the detailed response!  The file `calendar.php` is indeed in the same folder as all the other files I downloaded, and in the same folder as the calendar file.  I added the `phpinfo` function to my test script as you suggested.  If I understand correctly, the following lines from the output of that script answer two out of three of your questions positively:

>  **Apache Environment**
>
>    HTTP_ACCEPT | text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 
>
>
> **libXML**
>
>    support | active 
>    libXML Compiled Version | 2.9.3
>    libXML Loaded Version | 20903
>    libXML streams | enabled

However, I can't find a subsection titled **dom**, and the only place where "dom" appears is in the section **PHP Credits**.  Does this mean that there is a module called "dom" missing from the installation, and that I need to  to ask my system administrator to add it?

**Comment by Frimkron** [comment]
@TentativeConvert Unfortunately yes, I think so. The `dom` extension is usually installed by default, but apparently it's possible to disable it when compiling and installing PHP, so your sys admin might have removed it for some reason. Let me know whether that solves it :slightly_smiling_face:

**Comment by TentativeConvert** [comment]
OK, thanks a lot! Will try this and get back to you.  This may take a while; feel free to close this issue in the meantime.

**Comment by TentativeConvert** [comment]
Installation of the `dom` extension by our system administrator indeed solved the problem.  Thanks a lot for your help!
