### ISSUE TITLE
Works local, but not on EC2

### ISSUE THREAD

**Issue by MNaake** [Frimkron/PHPCalFeed#9]
I am using the json import functionality.
On localhost everything works fine. I pushed it to GitHub and pulled it to my ec2 instance.
When I call the calendar.php all files get generated, so permissions should be alright.
So although everything seems fine the calendar in calendar.php does not have any events and no title.

What could be the issue?

**Comment by Frimkron** [comment]
Hi @MNaake. Did you resolve the issue? What was the cause? 🙂

**Comment by MNaake** [comment]
Yes I did. Sorry for not responding. Actually I didn’t read your instructions carefully enough. I just had to make sure that the write rights for the necessary folders exist. Thank you!
